#roles/dbserver/tasks/main.yaml
- name: Install PostgreSQL
  yum:
    name: postgresql-server
    state: present
- name: Initialize PostgreSQL database
  # Initialize the PostgreSQL database
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: true
- name: Get PostgreSQL version
  command: psql --version 

- name: get status of PostgreSQL service
  command: systemctl status postgresql